import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const CATEGORIES = [
  {
    slug: 'trading-cards',
    name: 'Cards & Blind Boxes',
    description: 'Holographic booster packs, acrylic slab displays & mystery capsules',
    colorTheme: 'magenta',
    iconName: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'vinyl-toys',
    name: 'Designer Vinyl Toys',
    description: 'Articulated mecha chibis, chrome rabbits & soft vinyl kaijus',
    colorTheme: 'lime',
    iconName: 'Bot',
    image: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'phone-charms',
    name: 'Y2K Phone Charms',
    description: 'Liquid metallic straps, mini tamagotchi charms & cyber carabiners',
    colorTheme: 'lavender',
    iconName: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'stickers-patches',
    name: 'Stickers & Patches',
    description: 'Holographic sticker bomb packs, chrome decals & chenille patches',
    colorTheme: 'blue',
    iconName: 'Sticker',
    image: 'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'plushies-apparel',
    name: 'Plushies & Wearables',
    description: 'Goth bunny backpacks, shoulder aliens & distressed acid beanies',
    colorTheme: 'magenta',
    iconName: 'Heart',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'desktop-tech',
    name: 'Desktop & Play Tech',
    description: 'Pixel art companions, RGB translucent keypads & flow neon lightbars',
    colorTheme: 'lime',
    iconName: 'Gamepad2',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
  },
];

const PRODUCTS = [
  // 1. TRADING CARDS & BLIND BOXES
  {
    slug: 'glitch-cyber-holo-booster-pack',
    name: 'GLITCHPOP Vol. 1 Holo Booster Pack',
    tagline: '10 Cards per pack · 1 Guaranteed Secret Rare Holo foil card',
    description: 'The inaugural physical card drop. 100-card base set printed on 350gsm premium German core cardstock with multi-layer cold-stamped holographic foil prism finish.',
    price: 1800, // $18.00
    compareAtPrice: 2400,
    categorySlug: 'trading-cards',
    stockCount: 42,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Prism Holo', hex: '#C9A9FF' },
      { name: 'Cyber Lime Edition', hex: '#C6FF3D' },
      { name: 'Hot Magenta Variant', hex: '#FF2E93' },
    ]),
    sizes: JSON.stringify(['Single Pack (10 Cards)', 'Blister Bundle (3 Packs)', 'Sealed Booster Box (24 Packs)']),
    tags: JSON.stringify(['bestseller', 'trending', 'limited']),
    vibes: JSON.stringify(['y2k', 'cybercore']),
    rarity: 'RARE',
    rating: 4.9,
    reviewsCount: 142,
    materials: '350gsm Black-Core German Cardstock, Multi-layer Refractive Foil',
    dimensions: '63mm × 88mm Standard TCG Size',
    careInstructions: 'Store in UV-protected acrylic sleeves or binder pages.',
    featured: true,
  },
  {
    slug: 'acrylic-slab-display-vault-stand',
    name: 'Magnetic Acrylic Card Slab Display Vault',
    tagline: 'UV-blocking magnetic enclosure for your grail card display',
    description: 'Heavyweight optical-grade crystal acrylic slab protector with 4 neodymium corner magnets. Blocks 99% UV radiation to preserve your rarest holographic cards from fading.',
    price: 2400,
    compareAtPrice: 3000,
    categorySlug: 'trading-cards',
    stockCount: 28,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Crystal Clear', hex: '#FFFFFF' },
      { name: 'Smoke Tint', hex: '#27272A' },
      { name: 'Neon Cyber Blue', hex: '#3D7EFF' },
    ]),
    sizes: JSON.stringify(['35pt Standard', '75pt Relic / Patch', '100pt Extra Thick']),
    tags: JSON.stringify(['new', 'essential']),
    vibes: JSON.stringify(['cybercore', 'y2k']),
    rarity: 'COMMON',
    rating: 4.8,
    reviewsCount: 65,
    materials: 'Optical Cast Acrylic, 4× N52 Neodymium Magnets',
    dimensions: '110mm × 73mm × 8mm',
    careInstructions: 'Wipe with microfiber cloth. Avoid acetone or abrasive cleaners.',
    featured: false,
  },
  {
    slug: 'chibi-pixel-alien-blind-capsule',
    name: 'Pixel Invader Mystery Blind Box Capsule',
    tagline: '1 of 8 collectible vinyl micro-figures · 1/64 Secret Chase Variant',
    description: 'Each gashapon-style sealed capsule contains one articulated 2.5-inch micro vinyl figure with removable magnetic accessories and collectible art card.',
    price: 1500,
    compareAtPrice: 2000,
    categorySlug: 'trading-cards',
    stockCount: 35,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Random Surprise', hex: '#FF2E93' },
      { name: 'Collector Set (All 8)', hex: '#C6FF3D' },
    ]),
    sizes: JSON.stringify(['Single Blind Capsule', 'Full Carton (8 Capsules)']),
    tags: JSON.stringify(['trending', 'kawaii']),
    vibes: JSON.stringify(['kawaii', 'chaotic-good']),
    rarity: 'LIMITED',
    rating: 5.0,
    reviewsCount: 88,
    materials: 'Eco PVC, Soft Matte Finish, Rare Earth Magnet',
    dimensions: '65mm × 50mm Capsule',
    careInstructions: 'Keep away from extreme heat. Collect all 8 series characters.',
    featured: true,
  },
  {
    slug: 'secret-rare-holographic-cyber-dragon',
    name: 'Cyber Void Dragon — Secret Rare Grail Foil',
    tagline: 'Serialized 1st Edition #042/100 · Certified Mint Gem 10',
    description: 'The ultimate collector card from the GLITCHPOP Series 01. Full-art textured holographic foil with rainbow refraction foil borders. Ships pre-graded in serialized tamper-evident acrylic slab.',
    price: 12000, // $120.00
    compareAtPrice: 16000,
    categorySlug: 'trading-cards',
    stockCount: 4,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Prismatic Mirror Foil', hex: '#C9A9FF' },
      { name: 'Obsidian Black Gold', hex: '#FFD8BE' },
    ]),
    sizes: JSON.stringify(['Serialized Slab #042', 'Serialized Slab #078']),
    tags: JSON.stringify(['grail', 'limited', 'bestseller']),
    vibes: JSON.stringify(['cybercore', 'grunge']),
    rarity: 'GRAIL',
    rating: 5.0,
    reviewsCount: 34,
    materials: 'German Black-Core 350gsm, Micro-Etched Stamped Foil, Slab Acrylic',
    dimensions: 'Standard TCG Graded Slab (135mm × 82mm)',
    careInstructions: 'Hermetically sonic-welded slab. Do not submerge.',
    featured: true,
  },
  {
    slug: 'retro-prism-sticker-card-set',
    name: 'Y2K Prism Peel-Off Sticker Card Pack',
    tagline: 'Double-layer peelable vintage holographic stickers',
    description: 'Remember 90s arcade vending machines? Peel the top holographic layer to reveal a secret retro anime tech illustration underneath. 5 cards per sealed silver foil sleeve.',
    price: 1200,
    compareAtPrice: 1600,
    categorySlug: 'trading-cards',
    stockCount: 50,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Square Grid Prism', hex: '#3D7EFF' },
      { name: 'Stardust Holo', hex: '#FF2E93' },
    ]),
    sizes: JSON.stringify(['5-Card Pack', '20-Card Vault Box']),
    tags: JSON.stringify(['y2k', 'fun']),
    vibes: JSON.stringify(['y2k', 'kawaii']),
    rarity: 'COMMON',
    rating: 4.7,
    reviewsCount: 42,
    materials: 'Vinyl Gloss Sticker Overlay, Heavy Coated Cardstock',
    dimensions: '59mm × 86mm',
    careInstructions: 'Peel gently from bottom-left corner to reveal bottom layer.',
    featured: false,
  },

  // 2. DESIGNER VINYL TOYS
  {
    slug: 'cyberpunk-mecha-rabbit-vinyl-art-toy',
    name: 'Mecha Usagi — Cyberpunk Vinyl Art Figure',
    tagline: '7-inch designer vinyl with removable gas mask & LED visor',
    description: 'Sculpted by Tokyo underground toy collective. Features articulated arms and ears, magnetic interchangeable visor with light-up green cyberpunk eye implants, and matte spray finish.',
    price: 7800, // $78.00
    compareAtPrice: 9500,
    categorySlug: 'vinyl-toys',
    stockCount: 12,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Cyber Lime & Matte Black', hex: '#C6FF3D' },
      { name: 'Hot Magenta & Ghost White', hex: '#FF2E93' },
      { name: 'Raw Chrome Edition', hex: '#C9A9FF' },
    ]),
    sizes: JSON.stringify(['7-Inch Standard Edition', '11-Inch Studio Master']),
    tags: JSON.stringify(['bestseller', 'limited']),
    vibes: JSON.stringify(['cybercore', 'grunge']),
    rarity: 'LIMITED',
    rating: 4.9,
    reviewsCount: 110,
    materials: 'Soft Vinyl (Sofubi), ABS Plastic, Neodymium Magnets, CR2032 Battery',
    dimensions: '180mm × 110mm × 90mm',
    careInstructions: 'Dust with soft makeup brush. Keep away from direct sunlight.',
    featured: true,
  },
  {
    slug: 'glow-in-the-dark-radioactive-kaiju',
    name: 'Radioactive Lil Kaiju Glow Vinyl Toy',
    tagline: 'Charges in light · Radiates luminous radioactive green in the dark',
    description: 'Hand-poured Japanese soft vinyl infused with extra-concentrated phosphor pigment. Expose to ambient light for 60 seconds and watch it illuminate your desk all night long.',
    price: 4800,
    compareAtPrice: 6000,
    categorySlug: 'vinyl-toys',
    stockCount: 18,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Nuclear Green Glow', hex: '#C6FF3D' },
      { name: 'Ultraviolet Blue Glow', hex: '#3D7EFF' },
    ]),
    sizes: JSON.stringify(['4.5-Inch Chubby']),
    tags: JSON.stringify(['trending', 'kawaii']),
    vibes: JSON.stringify(['kawaii', 'weirdcore']),
    rarity: 'RARE',
    rating: 4.9,
    reviewsCount: 76,
    materials: 'Japanese Slush-Cast Sofubi Vinyl, Non-Toxic Phosphor Powder',
    dimensions: '115mm × 95mm × 85mm',
    careInstructions: 'Recharges forever under UV or sunlight. Wash with mild soap.',
    featured: false,
  },
  {
    slug: 'metallic-streetwear-doberman-sculpture',
    name: 'Guard Dog 2077 — Electroplated Chrome Figure',
    tagline: 'Mirrored electroplated chrome finish with spiked collar',
    description: 'Sleek angular polygonal canine sculpture electroplated in mirror-grade liquid silver chrome. Weighted solid resin core feels heavy and luxurious on any shelf or battlestation.',
    price: 6400,
    compareAtPrice: 8000,
    categorySlug: 'vinyl-toys',
    stockCount: 9,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Liquid Mirror Chrome', hex: '#C9A9FF' },
      { name: 'Anodized Cyber Violet', hex: '#FF2E93' },
    ]),
    sizes: JSON.stringify(['8-Inch Heavyweight']),
    tags: JSON.stringify(['grail', 'edc']),
    vibes: JSON.stringify(['cybercore', 'y2k']),
    rarity: 'GRAIL',
    rating: 5.0,
    reviewsCount: 52,
    materials: 'High-Density Polyresin, Vacuum Electroplated Chrome Layer',
    dimensions: '200mm × 140mm × 80mm (680 grams)',
    careInstructions: 'Handle with cotton gloves or microfiber to avoid fingerprints.',
    featured: true,
  },
  {
    slug: 'translucent-alien-slime-art-figure',
    name: 'Gloopie — Clear Slime Resin Monster',
    tagline: 'Suspended holographic glitter & mini bones inside clear resin',
    description: 'Cast in crystal-clear water-clear polyurethane resin with internal suspended holographic glitter flakes and tiny glow-in-the-dark skeleton parts. Every piece is unique.',
    price: 3600,
    compareAtPrice: 4500,
    categorySlug: 'vinyl-toys',
    stockCount: 22,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Grape Slime', hex: '#C9A9FF' },
      { name: 'Toxic Lime', hex: '#C6FF3D' },
      { name: 'Bubblegum Pink', hex: '#FF2E93' },
    ]),
    sizes: JSON.stringify(['3.5-Inch Petite']),
    tags: JSON.stringify(['weirdcore', 'fun']),
    vibes: JSON.stringify(['weirdcore', 'chaotic-good']),
    rarity: 'COMMON',
    rating: 4.8,
    reviewsCount: 39,
    materials: 'Optically Clear Polyurethane Resin, Holographic Flakes',
    dimensions: '90mm × 80mm × 75mm',
    careInstructions: 'Keep in temperate dry space. Avoid prolonged direct UV.',
    featured: false,
  },
  {
    slug: 'pastel-goth-demon-cat-figurine',
    name: 'Kuro-Neko Cyber Horns Plush Hybrid Toy',
    tagline: 'Vinyl sculpted head paired with beanbag plush body',
    description: 'The ultimate kawaii-meets-grunge hybrid. Soft sculpted matte vinyl face with three glowing pink eyes and metallic horns, attached to a super-soft weighted plush body.',
    price: 4200,
    compareAtPrice: 5200,
    categorySlug: 'vinyl-toys',
    stockCount: 16,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Midnight & Neon Pink', hex: '#FF2E93' },
      { name: 'Pastel Lilac & Mint', hex: '#C9A9FF' },
    ]),
    sizes: JSON.stringify(['6-Inch Sitting']),
    tags: JSON.stringify(['kawaii', 'grunge']),
    vibes: JSON.stringify(['kawaii', 'grunge']),
    rarity: 'RARE',
    rating: 4.9,
    reviewsCount: 94,
    materials: 'Rotocast Vinyl, Polyester Microplush, Glass Microbeads',
    dimensions: '150mm × 120mm × 100mm',
    careInstructions: 'Spot clean plush with damp cloth. Wipe vinyl face gently.',
    featured: false,
  },

  // 3. Y2K PHONE CHARMS & KEYCHAINS
  {
    slug: 'liquid-metallic-tamagotchi-phone-charm',
    name: 'Mini Tamagotchi Liquid Shaker Phone Charm',
    tagline: 'Miniature retro virtual pet shell filled with holographic glitter oil',
    description: 'An authentic scale replica of a vintage 1997 virtual pet shell filled with mineral oil, floating metallic stars, and pixel heart sequins. Attaches to any phone case or bag zipper.',
    price: 1600,
    compareAtPrice: 2200,
    categorySlug: 'phone-charms',
    stockCount: 40,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Translucent Hot Pink', hex: '#FF2E93' },
      { name: 'Glacier Blue Chrome', hex: '#3D7EFF' },
      { name: 'Radioactive Lime', hex: '#C6FF3D' },
    ]),
    sizes: JSON.stringify(['Standard Strap (15cm)']),
    tags: JSON.stringify(['bestseller', 'y2k', 'tiktok-viral']),
    vibes: JSON.stringify(['y2k', 'kawaii']),
    rarity: 'COMMON',
    rating: 4.9,
    reviewsCount: 230,
    materials: 'Molded Acrylic, Food-Grade Mineral Oil, Braided Nylon Cord',
    dimensions: 'Charm: 40mm × 35mm, Cord: 120mm',
    careInstructions: 'Sonic-sealed leakproof capsule. Do not puncture.',
    featured: true,
  },
  {
    slug: 'chunky-acrylic-beaded-harajuku-strap',
    name: 'Harajuku Cyber Beaded Phone Wristlet',
    tagline: 'Hand-strung candy beads, metallic stars & barbed wire charms',
    description: 'Heavy-duty 7-strand steel core wire strung with chunky metallic star beads, iridescent bubble spheres, chrome dice, and miniature alloy butterfly charms. Holds up to 15kg load.',
    price: 2200,
    compareAtPrice: 2800,
    categorySlug: 'phone-charms',
    stockCount: 30,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Acid Pastel Mix', hex: '#C6FF3D' },
      { name: 'Cyberpunk Monochrome', hex: '#27272A' },
      { name: 'Electric Fairycore', hex: '#FF2E93' },
    ]),
    sizes: JSON.stringify(['Wristlet Loop (22cm)', 'Crossbody Strap (120cm)']),
    tags: JSON.stringify(['trending', 'grunge']),
    vibes: JSON.stringify(['grunge', 'y2k']),
    rarity: 'RARE',
    rating: 4.8,
    reviewsCount: 165,
    materials: 'High-Impact Acrylic, Zinc Alloy Pendants, Stainless Steel Wire',
    dimensions: '220mm Loop Length',
    careInstructions: 'Waterproof and sweat-resistant.',
    featured: false,
  },
  {
    slug: 'cybercore-carabiner-heavy-keychain',
    name: 'Anodized Mech Carabiner & Tag Keychain',
    tagline: 'Aircraft aluminum quick-release with woven nylon flight tag',
    description: 'Industrial-strength asymmetric locking carabiner in iridescent electroplated oil-slick finish. Includes a jacquard woven "REMOVE BEFORE MATRIX" pull tag and three split rings.',
    price: 2600,
    compareAtPrice: 3200,
    categorySlug: 'phone-charms',
    stockCount: 25,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Oil Slick Rainbow', hex: '#C9A9FF' },
      { name: 'Matte Cyber Black', hex: '#18181B' },
      { name: 'Acid Hazard Lime', hex: '#C6FF3D' },
    ]),
    sizes: JSON.stringify(['Standard EDC']),
    tags: JSON.stringify(['cybercore', 'limited']),
    vibes: JSON.stringify(['cybercore', 'grunge']),
    rarity: 'LIMITED',
    rating: 4.9,
    reviewsCount: 78,
    materials: '6061 Anodized Aircraft Aluminum, Heavy High-Density Nylon',
    dimensions: '85mm × 45mm Carabiner, 140mm Flight Tag',
    careInstructions: 'Lubricate spring hinge annually with dry silicone spray.',
    featured: true,
  },
  {
    slug: 'glow-holographic-alien-phone-tag',
    name: '3D Jelly Alien Glow Charm & Phone Loop',
    tagline: 'Soft squishy silicone alien head that glows in neon cyan',
    description: 'Soft-touch silicone alien mascot charm with liquid-filled squishy belly and reflective holographic lanyard strap. Compatible with all phone cases via included ultra-thin tether tab.',
    price: 1400,
    compareAtPrice: 1800,
    categorySlug: 'phone-charms',
    stockCount: 45,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Glow Neon Cyan', hex: '#3D7EFF' },
      { name: 'Glow Alien Green', hex: '#C6FF3D' },
      { name: 'Holo Magenta Glow', hex: '#FF2E93' },
    ]),
    sizes: JSON.stringify(['Universal Loop']),
    tags: JSON.stringify(['kawaii', 'fun']),
    vibes: JSON.stringify(['kawaii', 'weirdcore']),
    rarity: 'COMMON',
    rating: 4.8,
    reviewsCount: 112,
    materials: 'Medical-Grade Silicone, TPU Tether Tab, Woven Reflective Thread',
    dimensions: '45mm Alien, 100mm Strap',
    careInstructions: 'Rinse under warm water to clean.',
    featured: false,
  },
  {
    slug: 'spooky-bat-plush-carabiner-charm',
    name: 'Vampire Bat Mini Plush Keychain',
    tagline: 'Faux shearling bat wings with tiny silver fangs & metal bell',
    description: 'A pocket-sized gothic companion with poseable wired wings, embroidered pink heart nose, and antique silver hardware. Hang it from your belt loop, backpack, or handbag.',
    price: 1900,
    compareAtPrice: 2500,
    categorySlug: 'phone-charms',
    stockCount: 20,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Midnight Charcoal', hex: '#18181B' },
      { name: 'Pastel Lavender Goth', hex: '#C9A9FF' },
    ]),
    sizes: JSON.stringify(['One Size (12cm Wingspan)']),
    tags: JSON.stringify(['grunge', 'kawaii']),
    vibes: JSON.stringify(['grunge', 'kawaii']),
    rarity: 'RARE',
    rating: 4.9,
    reviewsCount: 83,
    materials: 'Faux Fur Minky Fabric, Alloy Clip, Internal Wire Skeleton',
    dimensions: '120mm Wingspan × 70mm Height',
    careInstructions: 'Spot clean only.',
    featured: false,
  },

  // 4. STICKER PACKS & PATCHES
  {
    slug: 'mega-50-pack-holographic-sticker-bomb',
    name: 'GLITCHPOP 50-Pack Mega Holo Sticker Bomb',
    tagline: '50 unique vinyl die-cut stickers with prismatic foil finish',
    description: 'The definitive sticker collection. 50 completely unique designs featuring pixel art, cybercore tribal graphics, glitch characters, and retro anime typography. 100% waterproof and scratchproof.',
    price: 2200, // $22.00
    compareAtPrice: 3200,
    categorySlug: 'stickers-patches',
    stockCount: 65,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Full Rainbow Holographic Pack', hex: '#C9A9FF' },
      { name: 'Glitch Cyber Black Foil Pack', hex: '#C6FF3D' },
    ]),
    sizes: JSON.stringify(['50-Sticker Pack', '100-Sticker Collector Tin']),
    tags: JSON.stringify(['bestseller', 'tiktok-viral']),
    vibes: JSON.stringify(['cybercore', 'y2k', 'chaotic-good']),
    rarity: 'COMMON',
    rating: 5.0,
    reviewsCount: 310,
    materials: '6-mil Thick Premium Laminated Vinyl, UV & Weatherproof Adhesive',
    dimensions: 'Stickers range from 5cm to 10cm',
    careInstructions: 'Dishwasher safe on water bottles. Safe on laptops, skateboards, and cars.',
    featured: true,
  },
  {
    slug: 'cyberpunk-chrome-glitch-decals',
    name: 'Chrome Matrix Glitch Decal Sheet (A4)',
    tagline: 'Metallic mirror chrome automotive-grade vinyl decals',
    description: 'Precision kiss-cut sheet of 24 chrome stickers with holographic edge dispersion. Perfect for decking out laptops, PC cases, consoles, and synthesizer gear.',
    price: 1500,
    compareAtPrice: 2000,
    categorySlug: 'stickers-patches',
    stockCount: 38,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Mirror Chrome Silver', hex: '#FFFFFF' },
      { name: 'Mirror Cyber Gold', hex: '#FFE066' },
      { name: 'Chameleon Violet/Teal', hex: '#3D7EFF' },
    ]),
    sizes: JSON.stringify(['A4 Sheet (210mm × 297mm)']),
    tags: JSON.stringify(['cybercore', 'edc']),
    vibes: JSON.stringify(['cybercore', 'y2k']),
    rarity: 'COMMON',
    rating: 4.8,
    reviewsCount: 77,
    materials: 'Cast Metallic Vinyl, Acrylic Solvent Adhesive',
    dimensions: '210mm × 297mm',
    careInstructions: 'Apply to clean, degreased surface for permanent bond.',
    featured: false,
  },
  {
    slug: 'chenille-pastel-goth-iron-on-patch',
    name: 'Glitch Star Chenille Fluffy Iron-On Patch',
    tagline: 'Fluffy vintage varsity chenille with metallic lurex outline',
    description: 'A tactile textural masterpiece. Ultra-dense plush chenille yarn in pastel lavender and electric pink, outlined in sparkling silver lurex embroidery. Iron-on or stitch onto denim and hoodies.',
    price: 1600,
    compareAtPrice: 2200,
    categorySlug: 'stickers-patches',
    stockCount: 26,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Pastel Lavender & Pink', hex: '#C9A9FF' },
      { name: 'Neon Toxic Lime & Black', hex: '#C6FF3D' },
    ]),
    sizes: JSON.stringify(['Small (8cm)', 'Jacket Backer (20cm)']),
    tags: JSON.stringify(['grunge', 'kawaii']),
    vibes: JSON.stringify(['grunge', 'kawaii']),
    rarity: 'RARE',
    rating: 4.9,
    reviewsCount: 62,
    materials: 'Chenille Loop Yarn, Metallic Thread, Heat-Seal Adhesive Backing',
    dimensions: '80mm × 80mm',
    careInstructions: 'Iron on high heat for 30 seconds with parchment cover. Wash cold inside out.',
    featured: false,
  },
  {
    slug: 'warning-high-voltage-cybercore-bumper',
    name: 'OVERSTIMULATED // Holographic Slap Sticker',
    tagline: 'Extra-long Japanese street warning aesthetic slap sticker',
    description: '30cm long heavy-gauge holographic vinyl bumper slap. Bold bilingual Japanese/English glitch hazard typography that shifts colors as cars or pedestrians pass by.',
    price: 900,
    compareAtPrice: 1200,
    categorySlug: 'stickers-patches',
    stockCount: 50,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Holo Caution Yellow', hex: '#FFE066' },
      { name: 'Holo Hazard Pink', hex: '#FF2E93' },
    ]),
    sizes: JSON.stringify(['Bumper Slap (30cm × 7cm)']),
    tags: JSON.stringify(['chaotic-good', 'cybercore']),
    vibes: JSON.stringify(['chaotic-good', 'cybercore']),
    rarity: 'COMMON',
    rating: 4.8,
    reviewsCount: 129,
    materials: '7-mil Automotive Vinyl, UV Laminate',
    dimensions: '300mm × 70mm',
    careInstructions: 'Outdoor rated for 5+ years without fading.',
    featured: false,
  },
  {
    slug: 'limited-run-glitch-foil-collector-card-pack',
    name: 'Artists of Glitchpop — Limited Foil Art Prints Set',
    tagline: 'Set of 6 signed postcards on 400gsm holographic soft-touch card',
    description: 'Curated gallery print set featuring original digital artwork from 6 indie illustrators. Stamped with limited numbering and embossed gold foil emblem.',
    price: 3200,
    compareAtPrice: 4000,
    categorySlug: 'stickers-patches',
    stockCount: 14,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Archive Portfolio Box Set', hex: '#C9A9FF' },
    ]),
    sizes: JSON.stringify(['6-Card Art Portfolio (A5)']),
    tags: JSON.stringify(['limited', 'grail']),
    vibes: JSON.stringify(['weirdcore', 'y2k']),
    rarity: 'GRAIL',
    rating: 5.0,
    reviewsCount: 41,
    materials: '400gsm Soft-Touch Velvet Silk Stock, Rainbow Foil Stamping',
    dimensions: '148mm × 210mm (A5)',
    careInstructions: 'Frame behind glass or keep in presentation portfolio box.',
    featured: true,
  },

  // 5. PLUSHIES & WEARABLES
  {
    slug: 'goth-bunny-puffy-backpack-plush',
    name: 'Kuromi Chaos Goth Bunny Plush Backpack',
    tagline: 'Oversized plush backpack with zippered compartment & chain straps',
    description: 'The showstopper accessory. Ultra-plush distressed black and lavender velvet bunny with stitched skull eye patches, removable silver curb chains, and secret padded compartment for phone and essentials.',
    price: 6800, // $68.00
    compareAtPrice: 8500,
    categorySlug: 'plushies-apparel',
    stockCount: 15,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Midnight & Lilac', hex: '#C9A9FF' },
      { name: 'Blood Pink & Black', hex: '#FF2E93' },
      { name: 'All-Black Goth', hex: '#18181B' },
    ]),
    sizes: JSON.stringify(['Standard 45cm Backpack']),
    tags: JSON.stringify(['bestseller', 'trending', 'tiktok-viral']),
    vibes: JSON.stringify(['grunge', 'kawaii']),
    rarity: 'LIMITED',
    rating: 4.9,
    reviewsCount: 198,
    materials: 'Silky Plush Velvet, Metal Carabiners & Chains, Heavy Nylon Straps',
    dimensions: '450mm × 280mm × 160mm',
    careInstructions: 'Spot clean with mild detergent. Do not machine wash.',
    featured: true,
  },
  {
    slug: 'pixel-alien-magnetic-shoulder-buddy',
    name: 'Pixel Alien Magnetic Shoulder Plush Buddy',
    tagline: 'Sits perched on your shoulder through your clothes with concealed magnet',
    description: 'Slip the fabric-wrapped metal plate under your hoodie or shirt, and your green pixel alien companion snaps firmly in place on your shoulder! Features embroidered expression and cute floppy antennae.',
    price: 2800,
    compareAtPrice: 3500,
    categorySlug: 'plushies-apparel',
    stockCount: 30,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Alien Slime Green', hex: '#C6FF3D' },
      { name: 'Cyber Blue Glitch', hex: '#3D7EFF' },
      { name: 'UFO Magenta Glow', hex: '#FF2E93' },
    ]),
    sizes: JSON.stringify(['One Size (15cm Buddy)']),
    tags: JSON.stringify(['fun', 'kawaii']),
    vibes: JSON.stringify(['kawaii', 'chaotic-good']),
    rarity: 'COMMON',
    rating: 4.8,
    reviewsCount: 147,
    materials: 'Micro-Velboa Plush, Dual N52 Strong Neodymium Magnets',
    dimensions: '150mm Height × 100mm Width',
    careInstructions: 'Safe on all clothing fabrics. Remove before washing clothes.',
    featured: false,
  },
  {
    slug: 'oversized-distressed-acid-wash-beanie',
    name: 'Cyber Slouch Acid Wash Knit Beanie',
    tagline: 'Chunky ribbed knit with safety pins & raw metallic star charms',
    description: 'Double-layered chunky knit cotton beanie with custom mineral wash fading. Adorned with detachable silver safety pins, star studs, and a custom woven GLITCHPOP brand label.',
    price: 3400,
    compareAtPrice: 4200,
    categorySlug: 'plushies-apparel',
    stockCount: 22,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Acid Washed Charcoal', hex: '#27272A' },
      { name: 'Distressed Lavender Bleach', hex: '#C9A9FF' },
      { name: 'Toxic Lime Fade', hex: '#C6FF3D' },
    ]),
    sizes: JSON.stringify(['One Size Slouch Fit']),
    tags: JSON.stringify(['trending', 'grunge']),
    vibes: JSON.stringify(['grunge', 'y2k']),
    rarity: 'RARE',
    rating: 4.9,
    reviewsCount: 115,
    materials: '100% Breathable Combed Cotton, Steel Hardware Charms',
    dimensions: '28cm Depth (Slouchy Fit)',
    careInstructions: 'Remove metallic charms before machine washing cold. Lay flat to dry.',
    featured: true,
  },
  {
    slug: 'chunky-y2k-resin-star-cocktail-ring',
    name: 'Liquid Chrome Puffy Star Resin Ring',
    tagline: 'Chunky 90s statement ring with floating glitter & chrome star core',
    description: 'A bold nostalgic Y2K chunky ring cast from crystal jewelry resin with an electroplated chrome star suspended in liquid-effect core. Guaranteed to trigger compliments.',
    price: 1800,
    compareAtPrice: 2400,
    categorySlug: 'plushies-apparel',
    stockCount: 35,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Holo Pink Glitter', hex: '#FF2E93' },
      { name: 'Alien Slime Green', hex: '#C6FF3D' },
      { name: 'Ice Chrome Clear', hex: '#FFFFFF' },
    ]),
    sizes: JSON.stringify(['Size 6 (Small)', 'Size 7 (Medium)', 'Size 8 (Large)']),
    tags: JSON.stringify(['y2k', 'tiktok-viral']),
    vibes: JSON.stringify(['y2k', 'kawaii']),
    rarity: 'COMMON',
    rating: 4.7,
    reviewsCount: 89,
    materials: 'Hypoallergenic Jewelry Resin, Chrome Alloy Core',
    dimensions: 'Top Star: 30mm × 30mm',
    careInstructions: 'Water resistant. Remove before applying lotions or sanitizer.',
    featured: false,
  },
  {
    slug: 'liquid-metallic-holographic-crossbody',
    name: 'Hyper-Reflective Holographic Moon Bag',
    tagline: 'Shifts from silver to blinding rainbow prism under direct light',
    description: 'Constructed from aerospace-grade prism TPU that explodes into vivid multi-color rainbow reflections under direct flash or sunlight. Fits water bottle, Nintendo Switch, and daily kit.',
    price: 5400,
    compareAtPrice: 6800,
    categorySlug: 'plushies-apparel',
    stockCount: 18,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Prismatic Silver Holo', hex: '#C9A9FF' },
      { name: 'Deep Oil-Slick Black', hex: '#18181B' },
    ]),
    sizes: JSON.stringify(['Medium Sling (32cm × 18cm)']),
    tags: JSON.stringify(['limited', 'cybercore']),
    vibes: JSON.stringify(['cybercore', 'y2k']),
    rarity: 'LIMITED',
    rating: 4.9,
    reviewsCount: 104,
    materials: 'Prismatic Holographic TPU, Waterproof YKK Zippers, Seatbelt Webbing',
    dimensions: '320mm × 180mm × 90mm',
    careInstructions: 'Wipe clean with microfiber cloth.',
    featured: true,
  },

  // 6. DESKTOP PLAY & AMBIENT TECH
  {
    slug: 'pixel-art-companion-bluetooth-speaker',
    name: 'Retro Pixel Matrix Hub & Mechanical Speaker',
    tagline: '16×16 programmable RGB pixel art animations & clicky mechanical keys',
    description: 'The undisputed king of aesthetic desk setups. Create custom pixel art animations, display real-time Spotify audio visualizers, and enjoy rich 360° sound driven by clicky tactile blue switches.',
    price: 6800, // $68.00
    compareAtPrice: 8500,
    categorySlug: 'desktop-tech',
    stockCount: 20,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Cyber Lime Shell', hex: '#C6FF3D' },
      { name: 'Pastel Bubblegum Pink', hex: '#FF2E93' },
      { name: 'Translucent Atomic Purple', hex: '#C9A9FF' },
    ]),
    sizes: JSON.stringify(['Standard 16×16 Matrix']),
    tags: JSON.stringify(['bestseller', 'trending']),
    vibes: JSON.stringify(['cybercore', 'kawaii', 'y2k']),
    rarity: 'RARE',
    rating: 4.9,
    reviewsCount: 320,
    materials: 'ABS Shell, Mechanical Blue Switches, 16×16 RGB LED Matrix, 3000mAh Battery',
    dimensions: '114mm × 114mm × 90mm',
    careInstructions: 'Recharge via included braided USB-C cable. Bluetooth 5.3.',
    featured: true,
  },
  {
    slug: 'translucent-rgb-mechanical-macro-keypad',
    name: 'Translucent 9-Key Haptic Macro Pad',
    tagline: 'Kailh box switches with rotary volume dial & full-spectrum RGB',
    description: 'Crystal-clear transparent casing exposing gold PCB circuits and Kailh box switches. Fully programmable hot-swappable macro keys for streaming, Discord mutes, gaming shortcuts, and satisfying fidgeting.',
    price: 3600,
    compareAtPrice: 4800,
    categorySlug: 'desktop-tech',
    stockCount: 25,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Crystal Clear', hex: '#FFFFFF' },
      { name: 'Smoke Tint', hex: '#27272A' },
      { name: 'Neon Cyber Blue', hex: '#3D7EFF' },
    ]),
    sizes: JSON.stringify(['9-Key + CNC Volume Dial']),
    tags: JSON.stringify(['trending', 'edc']),
    vibes: JSON.stringify(['cybercore', 'grunge']),
    rarity: 'COMMON',
    rating: 4.8,
    reviewsCount: 140,
    materials: 'Polycarbonate Casing, Gold-Plated Hot-Swap Sockets, Aluminum Knob',
    dimensions: '100mm × 100mm × 35mm',
    careInstructions: 'Compatible with Windows/Mac/Linux. Detachable Type-C braided cable.',
    featured: true,
  },
  {
    slug: 'sound-reactive-flow-neon-lightbar',
    name: 'Sound-Reactive RGB Flow Rhythm Bar',
    tagline: '32-bit ARM DSP chip tracks music beats with 32 independent color beads',
    description: 'High-sensitivity built-in microphone and AGC intelligent noise reduction. Displays mesmerizing fluid spectrum animations in real-time sync with whatever music or gaming audio is playing in your room.',
    price: 2600,
    compareAtPrice: 3400,
    categorySlug: 'desktop-tech',
    stockCount: 35,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Matte Cyber Black', hex: '#18181B' },
      { name: 'Frosted White Minimal', hex: '#FFFFFF' },
      { name: 'Anodized Silver Alloy', hex: '#C9A9FF' },
    ]),
    sizes: JSON.stringify(['Single 20cm Lightbar', 'Dual Stereo Pair (2 Bars)']),
    tags: JSON.stringify(['bestseller', 'room-upgrade']),
    vibes: JSON.stringify(['cybercore', 'chaotic-good']),
    rarity: 'COMMON',
    rating: 4.9,
    reviewsCount: 275,
    materials: 'Aluminum Alloy Shell, 32× Epistar RGB LEDs, 32-bit ARM Processor',
    dimensions: '181mm × 18mm × 15mm',
    careInstructions: 'USB-C powered with built-in rechargeable battery.',
    featured: false,
  },
  {
    slug: 'retro-translucent-atomic-handheld-console',
    name: 'Pocket Glitch 4K Handheld Emulation Console',
    tagline: 'Transparent atomic purple shell with 3.5" IPS display & 10,000 retro classics',
    description: 'Relive the golden era of 90s handheld gaming. Packed with 10,000 legendary 8-bit, 16-bit, and 32-bit classics inside a gorgeous translucent atomic purple shell with dual Hall-effect analog sticks.',
    price: 6400,
    compareAtPrice: 8000,
    categorySlug: 'desktop-tech',
    stockCount: 16,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Atomic Purple Translucent', hex: '#C9A9FF' },
      { name: 'Clear Smoke Black', hex: '#27272A' },
      { name: 'Neon Glitch Pink', hex: '#FF2E93' },
    ]),
    sizes: JSON.stringify(['64GB (5,000 Games)', '128GB (10,000 Games + PS1)']),
    tags: JSON.stringify(['y2k', 'bestseller']),
    vibes: JSON.stringify(['y2k', 'chaotic-good']),
    rarity: 'LIMITED',
    rating: 4.9,
    reviewsCount: 184,
    materials: 'Impact-Resistant Polycarbonate Shell, Quad-Core Cortex Chip, 3500mAh Battery',
    dimensions: '142mm × 76mm × 21mm',
    careInstructions: 'Charge with 5V/2A adapter. Includes 64GB MicroSD card.',
    featured: true,
  },
  {
    slug: 'magnetic-levitating-chromatic-moon-orb',
    name: 'Floating Magnetic Chromatic Moon Orb',
    tagline: 'Perpetually levitates and rotates in mid-air via electromagnetic coils',
    description: 'A genuine physics marvel. Suspended 15mm above its wood-tone base with zero wires, perpetually spinning while wireless electromagnetic induction lights up 16 RGB chromatic moon nebula states.',
    price: 7400,
    compareAtPrice: 9200,
    categorySlug: 'desktop-tech',
    stockCount: 11,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1534423861386-85a16f5d13fd?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify([
      { name: 'Chromatic Nebula Glow', hex: '#FF2E93' },
      { name: 'Lunar Warm White', hex: '#FFE066' },
    ]),
    sizes: JSON.stringify(['14cm Diameter Orb']),
    tags: JSON.stringify(['grail', 'room-upgrade']),
    vibes: JSON.stringify(['cybercore', 'weirdcore']),
    rarity: 'GRAIL',
    rating: 5.0,
    reviewsCount: 195,
    materials: 'High-Precision 3D Printed PLA Surface, Rare-Earth Magnets, Touch Base',
    dimensions: 'Globe: 140mm Diameter, Base: 134mm × 134mm × 28mm',
    careInstructions: 'Lower globe gently over center point until magnetic lock is felt.',
    featured: true,
  },
];

async function main() {
  console.log('⚡ Purging old database tables...');
  await prisma.order.deleteMany({});
  await prisma.product.deleteMany({});
  await prisma.category.deleteMany({});
  await prisma.newsletterSubscriber.deleteMany({});

  console.log('🌈 Seeding 6 GLITCHPOP Categories...');
  for (const cat of CATEGORIES) {
    await prisma.category.create({ data: cat });
  }

  console.log(`📦 Seeding ${PRODUCTS.length} GLITCHPOP Pop-Culture Products with Vibes & Rarities...`);
  for (const prod of PRODUCTS) {
    await prisma.product.create({ data: prod });
  }

  console.log('✨ GLITCHPOP Database Seeding Completed Successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
